language: node_js
node_js:
  - "0.12"
  - "iojs"
after_success:
  - ./node_modules/.bin/isparta cover ./node_modules/.bin/_mocha --include src/*.js --report lcovonly -- test/*.js -r babel/register && cat ./coverage/lcov.info | coveralls && rm -r ./coverage
